import { Bebas_Neue, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import { AuthContextProvider } from "./_utils/auth-context";

const inter = Inter({ subsets: ["latin"] });

const bebasNeue = Bebas_Neue({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Momentum",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bebasNeue.className}>
        {" "}
          <AuthContextProvider>
            <Navbar />
            {children}
          </AuthContextProvider>
      </body>
    </html>
  );
}
